import express from 'express';
import pingRoutes from './routes/ping.routes.js';
import authRoutes from './routes/auth.routes.js';
import rssSourceRoutes from './routes/rss-sources.routes.js';
import topicDomainRoutes from './routes/topic-domains.routes.js';
import topicKeywordsRoutes from './routes/topic-keywords.routes.js';
import llmConfigRoutes from './routes/llm-configs.routes.js';
import filterRoutes from './routes/filter.routes.js';
import schedulerRoutes from './routes/scheduler.routes.js';
import articleRoutes from './routes/articles.routes.js';
import articleProcessRoutes from './routes/article-process.routes.js';
import searchRoutes from './routes/search.routes.js';
import settingsRoutes from './routes/settings.routes.js';
import systemPromptRoutes from './routes/system-prompts.routes.js';
import dailySummaryRoutes from './routes/daily-summary.routes.js';
import typesRoutes from './routes/types.routes.js';
import journalsRoutes from './routes/journals.routes.js';
import keywordsRoutes from './routes/keywords.routes.js';
import logsRoutes from './routes/logs.routes.js';
import blacklistRoutes from './routes/blacklist.routes.js';
import telegramChatsRoutes from './routes/telegram-chats.routes.js';
import wechatRoutes from './routes/wechat.routes.js';

const router = express.Router();

router.use(pingRoutes);
router.use(authRoutes);
router.use(rssSourceRoutes);
router.use(topicDomainRoutes);
router.use(topicKeywordsRoutes);
router.use(llmConfigRoutes);
router.use(filterRoutes);
router.use(schedulerRoutes);
router.use(articleRoutes);
router.use(articleProcessRoutes);
router.use('/search', searchRoutes);
router.use(settingsRoutes);
router.use(systemPromptRoutes);
router.use(dailySummaryRoutes);
router.use(typesRoutes);
router.use(journalsRoutes);
router.use(keywordsRoutes);
router.use(logsRoutes);
router.use(blacklistRoutes);
router.use(telegramChatsRoutes);
router.use(wechatRoutes);

export default router;
